src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("commentaires")]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Il faut Ajouter un contenu")]
    #[Groups("commentaires")]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups("commentaires")]
    private ?\DateTimeInterface $date_creation;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups("commentaires")]
    private ?\DateTimeInterface $date_modification;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[Groups("commentaires")]
    private ?Blog $blog = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?User $user = null;

    #[ORM\Column]
    private ?int $nbSignaler = null;

    #[ORM\OneToMany(mappedBy: 'commentaire', targetEntity: Report::class, cascade:["persist","remove","merge"], orphanRemoval:true)]
    private Collection $reports;

    public function __construct()
    {
        $this->date_creation = new \DateTime();
        $this->date_modification = new \DateTime();
        $this->reports = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->date_modification;
    }

    public function setDateModification(\DateTimeInterface $date_modification): self
    {
        $this->date_modification = $date_modification;

        return $this;
    }

    public function getBlog(): ?Blog
    {
        return $this->blog;
    }

    public function setBlog(?Blog $blog): self
    {
        $this->blog = $blog;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNbSignaler(): ?int
    {
        return $this->nbSignaler;
    }

    public function setNbSignaler(int $nbSignaler): self
    {
        $this->nbSignaler = $nbSignaler;

        return $this;
    }

    /**
     * @return Collection<int, Report>
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports->add($report);
            $report->setCommentaire($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getCommentaire() === $this) {
                $report->setCommentaire(null);
            }
        }

        return $this;
    }

}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('contenu', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\User;
use App\Entity\Report;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\BlogRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\CommentaireRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CommentaireController extends AbstractController
{
    #[Route('/commentaire', name: 'app_commentaire')]
    public function index(): Response
    {
        return $this->render('commentaire/index.html.twig', [
            'controller_name' => 'CommentaireController',
        ]);
    }

    #[Route('/commentaire/delete/{id}', name: 'app_comment_delete', methods: ['POST', 'GET', 'DELETE'])]
    public function commentdelete($id, EntityManagerInterface $entityManager): Response{
        $comment = $entityManager->getRepository(Commentaire::class)->find($id);

        if (!$comment) {
            throw new NotFoundHttpException('Commentaire not found');
        }
        $entityManager->remove($comment);
        $entityManager->flush();

        $getSLUGofblog = $comment->getBlog()->getSlug();

        return $this->redirectToRoute('app_blog_show', ['slug'=>$getSLUGofblog]);
    }

    #[Route('/commentaire/edit/{id}', name: 'app_comment_edit', methods: ['GET', 'POST'])]
    public function editCommentaire(Request $request, $id, EntityManagerInterface $entityManager): Response{

        $commentaire = $entityManager->getRepository(Commentaire::class)->find($id);
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        $blog = $commentaire->getBlog();
        
        if($form->isSubmitted() && $form->isValid()){
            $em= $this ->getDoctrine()->getManager();

            $commentaire->setDateModification(new \DateTime());

            $em->persist($commentaire);
            $em->flush();

            $getSLUGofblog = $commentaire->getBlog()->getSlug();

            return $this->redirectToRoute('app_blog_show', ['slug'=>$getSLUGofblog]);
        }

        //number
        $cmt = $entityManager->getRepository(Commentaire::class);
        $getidofblog = $blog->getId();
        $number= $cmt->numberCommentsByBlog($getidofblog);

        return $this->render('commentaire/edit.html.twig',[
            'number' => $number,
            'commentaire' => $commentaire,
            'blog' => $blog,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/commentaire/report/{id}', name: 'app_comment_report', methods: ['GET', 'POST'])]
    public function reportComment(Request $request, Commentaire $comment): Response
    {
        $user = $this->getUser();
        $getSLUGofblog = $comment->getBlog()->getSlug();

        // Check if the user has already reported the comment
        $report = $this->getDoctrine()->getRepository(Report::class)->findOneBy([
            'commentaire' => $comment,
            'user' => $user,
        ]);

        if ($report) {
            $this->addFlash('error', 'You have already reported this comment.');

            return $this->redirectToRoute('app_blog_show', ['slug' => $getSLUGofblog]);
        }

        // Increment the reported field of the comment and save the report and comment entities
        $comment->setNbSignaler($comment->getNbSignaler() + 1);

        $report = new Report();
        $report->setCommentaire($comment);
        $report->setUser($user);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($report);
        $entityManager->persist($comment);
        $entityManager->flush();

        $this->addFlash('success', 'Comment reported.');

        return $this->redirectToRoute('app_blog_show', ['slug' => $getSLUGofblog]);
    }


    /*************************************************************************************************** */
    /*************************************************************************************************** */
    /*************************************************************************************************** */
    /*************************************************************************************************** */
    /*************************************************************************************************** */

    /*************************************************************************************************** */
    /*************************************************************************************************** */
    /*************************************************************************************************** */
    /*************************************************************************************************** */
    /*** JSON functions */


    #[Route('/SowCommentsJson/{id}', name: 'ListCommentsJson')]
    public function getCommentaires($id,CommentaireRepository $repo, NormalizerInterface $normalizerInterface){
        $comments=$repo->findBy(['blog' => $id]);
        $commentaireNormalises = $normalizerInterface->normalize($comments, 'json', ['groups' => "commentaires"]);

        $json =json_encode($commentaireNormalises);

        return new Response($json);
    }

    // addCommentaireJson/id?contenu=hello
    #[Route('/addCommentaireJson/{id}', name: 'addCommentaireJson')]
    public function addCommentaireJson($id,Request $request, NormalizerInterface $normalizerInterface,EntityManagerInterface $entityManager){
        $em=$this->getDoctrine()->getManager();

        $blog = $entityManager->getRepository(Blog::class)->find($id);

        $comment = new Commentaire();
        $comment-> setContenu($request->get('contenu'));
        $comment->setBlog($blog);
        $comment->setNbSignaler(0);
        $em->persist($comment);

        $em->flush();

        $jsoncontent = $normalizerInterface->normalize($comment, 'json', ['groups' => "commentaires"]);
        return new Response(json_encode($jsoncontent));
    }

    #[Route('/DeleteCommentaireJson/{id}', name: 'DeleteCommentaireJson')]
    public function DeleteCommentaireJson($id, Request $request, NormalizerInterface $normalizerInterface){
        $em = $this->getDoctrine()->getManager();
        $comment =$em->getRepository(Commentaire::class)->find($id);
        $em->remove($comment);
        $em->flush();

        $jsoncontent = $normalizerInterface->normalize($comment, 'json', ['groups' => "commentaires"]);
        return new Response("Blog deleted successfully" . json_encode($jsoncontent));
    }

    // EditCommentaireJson/id?contenu=hello
    #[Route('/EditCommentaireJson/{id}', name: 'EditCommentaireJson')]
    public function EditCommentaireJson(Request $request,$id, NormalizerInterface $normalizerInterface){
        $em=$this->getDoctrine()->getManager();
        $comment =$em->getRepository(Commentaire::class)->find($id);
        $comment-> setContenu($request->get('contenu'));
        $comment->setNbSignaler(0);

        $em->flush();

        $jsoncontent = $normalizerInterface->normalize($comment, 'json', ['groups' => "commentaires"]);
        return new Response("Blog updated successfully" . json_encode($jsoncontent));
    }

}

templates/commentaire/backcommentaire.html.twig
{% extends 'back.html.twig' %}
{% block title  %}
	Commentaires Backend
{% endblock %}
{% block body %}
	<div class="main-panel">
		<div class="content-wrapper">
			<div class="page-header">
				<h3 class="page-title">
					Commentaires
				</h3>
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item">
							<a href="#">Tables</a>
						</li>
					</ol>
				</nav>
			</div>

			<div class="col-lg-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Table des Commentaires</h4>
						<div class="d-flex justify-content-end mt-3 mb-3"></div>
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>Id Commentaire</th>
										<th>Contenu</th>
										<th>Date Creation</th>
										<th>Date Modification</th>
										<th>Nombre Users à Signaler ce commentaire</th>
										<th>Blog</th>
										
										<th>Actions</th>
									</tr>
								</thead>
								{% for commentaire in commentaire %}
									<tbody>
										<tr>
											<td>{{ commentaire.id }}</td>
											<td>{{ commentaire.contenu|slice(0, 10) }}</td>
											<td>{{ commentaire.dateCreation|date("m/d/Y") }}</td>
											<td>{{ commentaire.dateModification|date("m/d/Y") }}</td>


											<td>{{ commentaire.nbSignaler }}
												{% if commentaire.nbSignaler >= 5 %}
													<button style="margin-left: 30px;" type="button" class="btn btn-danger" data-toggle="modal" data-target="#signalerModal{{ loop.index }}">
														Passer a l'action =>
														<i class="mdi mdi-delete"></i>
													</button>
													<!-- Delete Modal -->
													<div class="modal fade" id="signalerModal{{ loop.index }}" tabindex="-1" role="dialog" aria-labelledby="signalerModalLabel" aria-hidden="true">
														<div class="modal-dialog" role="document">
															<div class="modal-content">

																<div class="modal-header">
																	<h5 class="modal-title" id="signalerModalLabel">Confirmation du supprission</h5>
																	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
																		<span aria-hidden="true">&times;</span>
																	</button>
																</div>
																<div class="modal-body">
																	Êtes-vous sûr de vouloir supprimer cet élément?
																</div>
																<div class="modal-footer">
																	<form method="post" action="{{ path('app_commentaire_backend_delete', {'id': commentaire.id}) }}">
																		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
																		<button type="submit" class="btn btn-danger">oui</button>
																	</form>
																	<button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
																</div>
															</div>
														</div>
													</div>
												{% endif %}
											</td>
											<td>
												<a href="{{ path('app_commentaire_blog_backend', {'id': commentaire.blog.id}) }}" class="btn btn-primary">
													<i class="mdi mdi-eye"></i>
												</a>
											</td>
											
											<td>
												<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ loop.index }}">
													<i class="mdi mdi-delete"></i>
												</button>
												<!-- Delete Modal -->
												<div class="modal fade" id="deleteModal{{ loop.index }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
													<div class="modal-dialog" role="document">
														<div class="modal-content">

															<div class="modal-header">
																<h5 class="modal-title" id="deleteModalLabel">Confirmation du supprission</h5>
																<button type="button" class="close" data-dismiss="modal" aria-label="Close">
																	<span aria-hidden="true">&times;</span>
																</button>	
															</div>
															<div class="modal-body">
																Êtes-vous sûr de vouloir supprimer cet élément?
															</div>
															<div class="modal-footer">
																<form method="post" action="{{ path('app_commentaire_backend_delete', {'id': commentaire.id}) }}">
																	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
																	<button type="submit" class="btn btn-danger">oui</button>
																</form>
																<button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
															</div>
														</div>
													</div>
												</div>
											</td>
										</tr>
									</tbody>
								{% endfor %}
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	<!-- partial --><script src="{{asset('assets/vendors/js/vendor.bundle.base.js')}}"> </script>
	<!-- endinject -->
	<!-- Plugin js for this page -->
	<!-- End plugin js for this page -->
	<!-- inject:js --><script src="{{asset('js/off-canvas.js')}}"> </script>
	<script src="{{asset('js/hoverable-collapse.js')}}"></script>
<script src="{{asset('js/misc.js')}}"></script>
	<script src="{{asset('js/settings.js')}}"></script>
	<script src="{{asset('js/todolist.js')}}"></script>
    <script src="{{asset('assets/vendorsassets/js/vendor.bundle.base.js')}}"></script>
			<!-- endinject -->
			<!-- Plugin js for this page -->
			<script src="{{asset('assets/vendors/chart.js/Chart.min.js')}}"></script>
			<script src="{{asset('assets/vendors/progressbar.js/progressbar.min.js')}}"></script>
			<script src="{{asset('assets/vendors/jvectormap/jquery-jvectormap.min.js')}}"></script>
			<script src="{{asset('assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
			<script src="{{asset('assets/vendors/owl-carousel-2/owl.carousel.min.js')}}"></script>
			<!-- End plugin js for this page -->
			<!-- inject:js -->
			<script src="{{asset('assets/js/off-canvas.js')}}"></script>
			<script src="{{asset('assets/js/hoverable-collapse.js')}}"></script>
			<script src="{{asset('assets/js/misc.js')}}"></script>
			<script src="{{asset('assets/js/settings.js')}}"></script>
			<script src="{{asset('assets/js/todolist.js')}}"></script>
			<!-- endinject -->
			<!-- Custom js for this page -->
			<script src="{{asset('assets/js/dashboard.js')}}"></script>

{% endblock %}

templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}
{% block title  %} Edit Commentaire {% endblock %}
{% block body %}
<link href="{{asset('css-min/soccer.min.css')}}" rel="stylesheet" type="text/css" />

<!--************************************************************************************************************************************************** -->
<!--************************************************************************************************************************************************** -->
<!--************************************************************************************************************************************************** -->
<!--************************************************************************************************************************************************** -->
    <!--CONTENT BEGIN-->
    <div class="content">
        <div class="container">
            <div class="row row-offcanvas row-offcanvas-left">

                <!--SIEDBAR BEGIN-->


                <!--NEWS SINGLE BEGIN-->

                <section class="news-single col-xs-12 col-sm-12 col-md-9">
                    <p class="hidden-md hidden-lg">
                        <button type="button" class="btn sidebar-btn" data-toggle="offcanvas" title="Toggle sidebar">sidebar</button>
                    </p>
                    <div class="item">
                        <div class="top-info">
                            <div class="date"><a >{{ blog.dateCreation|date("m/d/Y") }}</a> Par <a >Mason Carrington</a></div>
                            <div class="comment-quantity"> {{ number }} Commentaires</div>
                        </div>

                        <h1>{{ blog.titre }}</h1>
                        <div class="img-wrap">
                            <img src="{{ asset('blogImages/' ~ blog.imageBlog) }}">
                        </div>


                        <div class="post-text">
                            <p>{{ blog.contenu }}</p>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="tags">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <ul class="share-bar">
                                        <li class="facebook"><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
                                        <li class="twitter"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                        <li class="google"><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                        <div class="comments-wrap">
                            <h4>Commentaires</h4>
                            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                            <div class="comment-item">
                                <div class="avatar"><img src="{{ asset('blogImages/user.png') }}"></div>
                                <div class="info">
                                    <div class="date">
                                        <a>{{ commentaire.dateCreation|date("m/d/Y") }}</a> Par <a>Ian Finch</a> Modifier le <a>{{ commentaire.dateModification|date("m/d/Y") }}</a> 
                                    </div>
                                    <p>{{ commentaire.contenu }}</p>
                                </div>
                            </div>
                            {{ form_widget(form.contenu) }}
                            <div class="text-danger" > {{ form_errors(form.contenu) }} </div>
                            <div class="tags">
                                <a class="comment-submit"><button type='submit' style="background:none; boarder:none; color: inherit;
                                                            border: none;
                                                            padding: 0;
                                                            font: inherit;
                                                            cursor: pointer;
                                                            outline: inherit;"> Editer</button></a>
                            </div>
                            {{ form_end(form) }}
                            <br>
                            <br>
                            <br>
                            
                        </div>
                    </div>
                </section>

                <!--NEWS SINGLE END-->

            </div>
        </div>
    </div>

<!--************************************************************************************************************************************************** -->
<!--************************************************************************************************************************************************** -->
<!--************************************************************************************************************************************************** -->
<!--************************************************************************************************************************************************** -->
<!--************************************************************************************************************************************************** -->


{% endblock %}

templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<link href="{{asset('css-min/soccer.min.css')}}" rel="stylesheet" type="text/css" />
{% endblock %}