src/Entity/Equipe.php
<?php

namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Serializer\Annotation\Groups;
#[ORM\Entity(repositoryClass: EquipeRepository::class)]
#[UniqueEntity(fields: ['nom_equipe'], message: 'nom d equipe déja utilisé')]
class Equipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)] 
    #[Assert\NotBlank(message:"veuillez choisir un nom d equipe")]
    private ?string $nom_equipe = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"veuillez choisir une description d'equipe")]
    private ?string $description_equipe = null;

    #[ORM\Column]
     /**
     * @ORM\Column(type="integer")
     
     * @Assert\NotBlank(message="Le nombre de joueurs est obligatoire")
     */
    private ?int $nb_joueurs = null;

    #[ORM\Column(length: 255)]
    private ?string $logo_equipe = null;

    #[ORM\Column(length: 255)]
    
    #[Assert\NotBlank(message:"veuillez choisir un site web")]
    private ?string $site_web = null;

    #[ORM\OneToMany(mappedBy: 'id_equipe', targetEntity: Sponsor::class, cascade: ["remove"], orphanRemoval: true)]
    private Collection $sponsors;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
     /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\ManyToOne(inversedBy: 'equipes')]
    private ?Joueur $joueur = null; 

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Jaime::class, cascade:["persist","remove","merge"], orphanRemoval:true)]
    private Collection $jaimes;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Jaimepas::class, cascade:["persist","remove","merge"], orphanRemoval:true)]
    private Collection $jaimepas;

    #[ORM\OneToMany(mappedBy: 'equipe1', targetEntity: Matches::class,cascade:['remove'],orphanRemoval: true)]
    private Collection $nomEquipe1;

    #[ORM\OneToMany(mappedBy: 'equipe2', targetEntity: Matches::class,cascade:['remove'],orphanRemoval: true)]
    private Collection $nomEquipe2;

    public function __construct()
    {
        $this->sponsors = new ArrayCollection();
        $this->jaimes = new ArrayCollection();
        $this->jaimepas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEquipe(): ?string
    {
        return $this->nom_equipe;
    }

    public function setNomEquipe(string $nom_equipe): self
    {
        $this->nom_equipe = $nom_equipe;

        return $this;
    }

    public function getDescriptionEquipe(): ?string
    {
        return $this->description_equipe;
    }

    public function setDescriptionEquipe(string $description_equipe): self
    {
        $this->description_equipe = $description_equipe;

        return $this;
    }

    public function getNbJoueurs(): ?int
    {
        return $this->nb_joueurs;
    }

    public function setNbJoueurs(int $nb_joueurs): self
    {
        $this->nb_joueurs = $nb_joueurs;

        return $this;
    }

    public function getLogoEquipe(): ?string
    {
        return $this->logo_equipe;
    }

    public function setLogoEquipe(string $logo_equipe): self
    {
        $this->logo_equipe = $logo_equipe;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(string $site_web): self
    {
        $this->site_web = $site_web;

        return $this;
    }

    public function __toString()
    {
        return $this->nom_equipe;
    }

    /**
     * @return Collection<int, Sponsor>
     */
    public function getSponsors(): Collection
    {
        return $this->sponsors;
    }

    public function addSponsor(Sponsor $sponsor): self
    {
        if (!$this->sponsors->contains($sponsor)) {
            $this->sponsors->add($sponsor);
            $sponsor->setIdEquipe($this);
        }

        return $this;
    }

    public function removeSponsor(Sponsor $sponsor): self
    {
        if ($this->sponsors->removeElement($sponsor)) {
            // set the owning side to null (unless already changed)
            if ($sponsor->getIdEquipe() === $this) {
                $sponsor->setIdEquipe(null);
            }
        }

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }
/**
     * @ORM\PrePersist()
     */
    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection<int, Jaime>
     */
    public function getJaimes(): Collection
    {
        return $this->jaimes;
    }

    public function addJaime(Jaime $jaime): self
    {
        if (!$this->jaimes->contains($jaime)) {
            $this->jaimes->add($jaime);
            $jaime->setEquipe($this);
        }

        return $this;
    }

    public function removeJaime(Jaime $jaime): self
    {
        if ($this->jaimes->removeElement($jaime)) {
            // set the owning side to null (unless already changed)
            if ($jaime->getEquipe() === $this) {
                $jaime->setEquipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Jaimepas>
     */
    public function getJaimepas(): Collection
    {
        return $this->jaimepas;
    }

    public function addJaimepa(Jaimepas $jaimepas): self
    {
        if (!$this->jaimepas->contains($jaimepas)) {
            $this->jaimepas->add($jaimepas);
            $jaimepas->setEquipe($this);
        }

        return $this;
    }

    public function removeJaimepa(Jaimepas $jaimepas): self
    {
        if ($this->jaimepas->removeElement($jaimepas)) {
            // set the owning side to null (unless already changed)
            if ($jaimepas->getEquipe() === $this) {
                $jaimepas->setEquipe(null);
            }
        }

        return $this;
    }

    public function getJoueur(): ?Joueur
    {
        return $this->joueur;
    }

    public function setJoueur(?Joueur $joueur): self
    {
        $this->joueur = $joueur;

        return $this;
    }

    public function getTotalJaimes(): int
    {
        return count($this->jaimes);
    }
 
    public function getTotaljaimepas(): int
    {
        return count($this->jaimepas);
    }

    public function isLikedByJoueur(Joueur $joueur): bool
    {
        foreach ($this->jaimes as $jaimes) {
            if ($jaimes->getJoueur() === $joueur) {
                return true;
            }
        }

        return false;
    }

    public function isDislikedByJoueur(Joueur $joueur): bool
    {
        foreach ($this->jaimepas as $jaimepas) {
            if ($jaimepas->getJoueur() === $joueur) {
                return true;
            }
        }

        return false;
    }


    public function like(Joueur $joueur): void
    {
        if (!$this->isLikedByJoueur($joueur)) {
            $jaimes = new Jaime();
            $jaimes->setEquipe($this);
            $jaimes->setJoueur($joueur);
            $this->jaimes[] = $jaimes;
        }
    }


    public function dislike(Joueur $joueur): void
    {
        if (!$this->isDislikedByJoueur($joueur)) {
            $Jaimepas = new Jaimepas();
            $Jaimepas->setEquipe($this);
            $Jaimepas->setJoueur($joueur);

            $this->jaimepas[] = $Jaimepas;
        }
    }
}

src/Controller/EquipeController.php
<?php

namespace App\Controller;

use App\Entity\Equipe;
use App\Form\EquipeType;
use App\Form\DateType;
use App\Form\SearchEquipeType;
use App\Form\SearchJoueurType;
use App\Entity\Likeseq;
use App\Entity\Jaime;
use App\Entity\Jaimepas;
use App\Repository\EquipeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ORM\EntityManagerInterface;    
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

#[Route('/equipe')]
class EquipeController extends AbstractController
{

    
    #[Route('/', name: 'app_equipe_index', methods: ['GET', 'POST'])]
    public function index(
        EquipeRepository $equipeRepository,
        PaginatorInterface $paginator,
        Request $request,
        EntityManagerInterface $em
        ): Response
    {

        //search form
        $form = $this->createForm(SearchEquipeType::class);
        $form->handleRequest($request);

        $sortOrder = $request->query->get('sort_order', 'asc');
        $sortBy = $request->query->get('sort_by', 'nom_equipe');

        // Create the query builder and add the orderBy clause
        $queryBuilder = $em->getRepository(Equipe::class)->createQueryBuilder('e');
        $queryBuilder->orderBy("e.$sortBy", $sortOrder);
        
        $data = $equipeRepository->findAll();
        $equipes = $paginator->paginate (

          $queryBuilder,
          $request->query->getInt('page',1),
          4

        );

        $hotequipes= $em->getRepository(Jaime::class)->findTopLikedEquipes();
        if($form->isSubmitted() && $form->isValid()){
            $data = $form->getData();
            $query = $em->getRepository(Equipe::class)
                ->createQueryBuilder('e')
                ->where('e.nom_equipe LIKE :query OR e.nb_joueurs LIKE :query')
                ->setParameter('query', "%{$data['query']}%")
                ->getQuery();

            $equipes= $paginator->paginate(
                $query,
                $request->query->getInt('page', 1),
                4
            );
            return $this->render('equipe/index.html.twig', [
                'form' => $form->createView(),
                'hotequipes' => $hotequipes,
                'equipes' => $equipes,
                'sort_order' => $sortOrder,
            'sort_by' => $sortBy,   
            ]);
        }
        
        return $this->render('equipe/index.html.twig', [
            'form' => $form->createView(),
            'equipes' => $equipes,
            'hotequipes' => $hotequipes,
            'sort_order' => $sortOrder,
            'sort_by' => $sortBy,
        ]);


    }

    #[Route('/equipelike/{id}', name: 'app_equipe_like', methods: ['POST', 'GET', 'DELETE'])]
    public function likeEquipe(Request $request, Equipe $equipe, EntityManagerInterface $entityManager,$id): Response{
      
        $joueur = $this->getUser();
        if (!$joueur) {
            throw new AccessDeniedHttpException();
        }
      
        $jaime = $entityManager->getRepository(Jaime::class)->findOneBy(['equipe' => $equipe, 'joueur' => $joueur]);

        if ($jaime) {
            $entityManager->remove($jaime);
        } else {
            $equipe->like($joueur);
        }

        $jaimepa = $entityManager->getRepository(Jaimepas::class)->findOneBy(['equipe' => $equipe, 'joueur' => $joueur]);

        if ($jaimepa) {
            $entityManager->remove($jaimepa);
            $equipe->like($joueur);
        }
        $entityManager->flush();

        $equipe = $entityManager->getRepository(Equipe::class)->find($id);

        return $this->redirectToRoute('app_equipe_index');
    }

    #[Route('/equipedislike/{id}', name: 'app_equipe_dislike', methods: ['POST', 'GET', 'DELETE'])]
    public function dislikeequipe(Request $request,$id,Equipe $equipe, EntityManagerInterface $entityManager): Response
    {

        $joueur = $this->getUser();
        if (!$joueur) {
            throw new AccessDeniedHttpException();
        }

        $jaimepa = $entityManager->getRepository(Jaimepas::class)->findOneBy(['equipe' => $equipe, 'joueur' => $joueur]);

        if ($jaimepa) {
            $entityManager->remove($jaimepa);
        } else {
            $equipe->dislike($joueur);
        }

        $jaime = $entityManager->getRepository(Jaime::class)->findOneBy(['equipe' => $equipe, 'joueur' => $joueur]);

        if ($jaime) {
            $entityManager->remove($jaime);
            $equipe->dislike($joueur);
        }
        $entityManager->flush();

        $equipe = $entityManager->getRepository(Equipe::class)->find($id);
        

        return $this->redirectToRoute('app_equipe_index');
    }

    #[Route('/search', name: 'search', methods: ['GET'])]
    public function search(Request $request, EquipeRepository $equipeRepository): JsonResponse
    {
        $criteria = $request->get('criteria');
        $searchTerm = $request->get('query');

        switch ($criteria) {
            case 'name':
                $results = $equipeRepository->findByNom($searchTerm);
                break;
            case 'description':
                $results = $equipeRepository->findByEmail($searchTerm);
                break;
            
            default:
                $results = [];
        }

        $data = [];

        foreach ($results as $result) {
            $data[] = [
                'id' => $result->getId(),
                'name' => $result->getNomEquipe(),
                'description' => $result->getDescriptionEquipe(),
                
            ];
        }

        return new JsonResponse($data);
    }


    #[Route('/recherche/{id}', name: 'app_equipe_recherche', methods: ['GET'])]
    public function searchaction (Request $request)
    {
        
            $entityManager = $this->getDoctrine()->getManager();
            $requestString = $request->query->get('q');
            $equipe =  $entityManager->getRepository(Equipe::class)->findEntitiesByString($requestString);
            
            if (!$equipe) {
                $result['equipe']['error'] = "equipe introuvable :( ";
            } else {
                $result['equipe'] = $this->getRealEntities($equipe);
            }
            
            return new Response(json_encode($result));
        }
        
        private function getRealEntities($equipe)
        {
            foreach ($equipe as $equipes) {
                $realEntities[$equipes->getId()] = [$equipes->getLogoEquipe(), $equipes->getNomEquipe()];
            }
            
            return $realEntities;
        }

    #[Route('/new', name: 'app_equipe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EquipeRepository $equipeRepository): Response
    {
        $equipe = new Equipe();
        $form = $this->createForm(EquipeType::class, $equipe);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $file */
            $file = $form->get('logo_equipe')->getData();
            // If a file was uploaded
            if ($file) {
                $filename = uniqid() . '.' . $file->guessExtension();

                // Move the file to the directory where brochures are stored
                $file->move(
                    'equipeImages',
                    $filename
                );
                // Update the 'image' property to store the image file name
                // instead of its contents
                $equipe->setLogoEquipe($filename);
            }
            $equipe->setDateCreation(new \DateTime());
            $equipeRepository->save($equipe, true);
            return $this->redirectToRoute('app_equipe_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('equipe/new.html.twig', [
            'equipe' => $equipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_equipe_show', methods: ['GET'])]
     public function show(Equipe $equipe , $id): Response
    {
        $entityManager=$this->getDoctrine()->getManager();

        $equipe = $entityManager->getRepository(Equipe::class)->find($id);
          //number dislikes
          $jaimepa = $entityManager->getRepository(Jaimepas::class);
          $numberDislikes= $jaimepa->numberDislikesByEquipe($id);
  
          //number likes
          $jaime = $entityManager->getRepository(Jaime::class);
          $numberLikes= $jaime->numberLikesByEquipe($id);

          

        return $this->render('equipe/show.html.twig', [
            'equipe' => $equipe,
            
            'numberLikes' => $numberLikes,
            'numberDislikes' => $numberDislikes,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_equipe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Equipe $equipe, EquipeRepository $equipeRepository): Response
    {
        $form = $this->createForm(EquipeType::class, $equipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             /** @var UploadedFile $file */
             $file = $form->get('logo_equipe')->getData();
             // If a file was uploaded
             if ($file) {
                 $filename = uniqid() . '.' . $file->guessExtension();
                 // Move the file to the directory where brochures are stored
                 $file->move(
                     'equipeImages',
                     $filename
                 );
                 // Update the 'image' property to store the image file name
                 // instead of its contents
                 $equipe->setLogoEquipe($filename);
             }

templates/equipe/_delete_form.html.twig
 
<form method="post" action="{{ path('app_equipe_delete', {'id': equipe.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet élément ?')">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equipe.id) }}">
    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"><i class="mdi mdi-delete"></i></button>


</form>
 
 

templates/equipe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/equipe/backindex.html.twig
{% extends 'back.html.twig' %}

{% block title %}Equipe index{% endblock %}

{% block body %}
    <h1>Equipe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_equipe</th>
                <th>Description_equipe</th>
                <th>Nb_joueurs</th>
                <th>Logo_equipe</th>
                <th>Site_web</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for equipe in equipes %}
            <tr>
                <td>{{ equipe.id }}</td>
                <td>{{ equipe.nomEquipe }}</td>
                <td>{{ equipe.descriptionEquipe }}</td>
                <td>{{ equipe.nbJoueurs }}</td>
                <td>{{ equipe.logoEquipe }}</td>
                <td>{{ equipe.siteWeb }}</td>
                <td>
                    <a href="{{ path('app_equipe_show', {'id': equipe.id}) }}">show</a>
                    <a href="{{ path('app_equipe_edit', {'id': equipe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_equipe_new') }}">Create new</a>
{% endblock %}

templates/equipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Equipe{% endblock %}

{% block body %}
    <h1>Modifier Equipe</h1>

    {{ include('equipe/_form.html.twig', {'button_label': 'Modifier'}) }}

   <div class="item"> <a href="{{ path('app_equipe_index') }}" class="btn small club-top-btn">retour à la liste</a> </div>

   
{% endblock %}

templates/equipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Equipe{% endblock %}

{% block body %}
    <h1>Ajouter une equipe</h1>
<center><div class="leave-comment-wrap">
{{ form_start(form) }}
<div class="row">
								<div class="col-md-12">
									<div class="item">
<label>
											<span>Nom equipe
												<i>*</i>
											</span>
											{{ form_widget(form.nom_equipe) }}
                                  {{ form_errors(form.nom_equipe) }}

										</label>
	</div>
								</div>

							<div class="col-md-12">
									<div class="item">	
										<label>
											<span>description de l'equipe
												<i>*</i>
											</span>
											{{ form_widget(form.description_equipe) }}
											{{ form_errors(form.description_equipe) }}
										</label>
											</div>
								</div>

							<div class="col-md-12">
									<div class="item">	
<label>
											<span>nombres de joueurs
                                            <i>*</i>
                                            </span>
											{{ form_widget(form.nb_joueurs) }}
											{{ form_errors(form.nb_joueurs) }}
										</label>
	</div>
								</div>
<div class="col-md-12">
									<div class="item">

										<label>
											<span>logo de l'equipe
												<i>*</i>
											</span>
											{{ form_widget(form.logo_equipe) }}
											{{ form_errors(form.logo_equipe) }}
										</label>

							</div>
								</div>

						<div class="col-md-12">
									<div class="item">						
<label>
											<span>SITE WEB
												<i>*</i>
											</span>
											{{ form_widget(form.site_web) }}
											 {{ form_errors(form.site_web) }}
										</label>
</div>
								</div>

								<div class="col-md-12">
									<div class="item">						
 {#
<label>
											<span>date de creation
												<i>*</i>
											</span>
											{{ form_widget(form.date_creation) }}
											 {{ form_errors(form.date_creation) }}
										</label>
										#}
</div>
								</div>

<div class="col-md-12">
									<div class="item">

</div>
								</div>
										

    {{ include('equipe/_form.html.twig') }}
    <a class="btn" href="{{ path('app_equipe_index') }}">Retour à la liste</a>
{{form_end(form)}}

		
{% endblock %}

templates/equipe/pagination.html.twig
{% if pageCount > 1 %}
    <nav>
        {% set classAlign = (align is not defined) ? '' : align=='center' ? ' justify-content-center' : (align=='right' ? ' justify-content-end' : '') %}
        {% set classSize = (size is not defined) ? '' : size=='large' ? ' pagination-lg' : (size=='small' ? ' pagination-sm' : '') %}
        <ul class="pagination{{ classAlign }}{{ classSize }}">

            {% if previous is defined %}
                <li class="page-item">
                    <a class="fa fa-chevron-left" rel="prev" href="{{ path(route, query|merge({(pageParameterName): previous})) }}">{{ ''|trans({}, 'KnpPaginatorBundle') }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="fa fa-chevron-left">{{ ''|trans({}, 'KnpPaginatorBundle') }}</span>
                </li>
            {% endif %}

            {% if startPage > 1 %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 1})) }}">1</a>
                </li>
                {% if startPage == 3 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 2})) }}">2</a>
                    </li>
                {% elseif startPage != 2 %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% endif %}
            {% endif %}

            {% for page in pagesInRange %}
                {% if page != current %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <span class="page-link">{{ page }}</span>
                    </li>
                {% endif %}

            {% endfor %}

            {% if pageCount > endPage %}
                {% if pageCount > (endPage + 1) %}
                    {% if pageCount > (endPage + 2) %}
                        <li class="page-item disabled">
                            <span class="page-link">&hellip;</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): (pageCount - 1)})) }}">{{ pageCount -1 }}</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): pageCount})) }}">{{ pageCount }}</a>
                </li>
            {% endif %}

            {% if next is defined %}
                <li class="page-item">
                    <a class="fa fa-chevron-right" rel="next" href="{{ path(route, query|merge({(pageParameterName): next})) }}">{{ ''|trans({}, 'KnpPaginatorBundle') }}</a>
                </li>
            {% else %}
                <li  class="page-item disabled">
                    <span class="fa fa-chevron-right">{{ ''|trans({}, 'KnpPaginatorBundle') }}</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/equipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Equipe{% endblock %}

{% block body %}
   <section class="club-wrap club-champ">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <h4>Détails de l'equipe </h4>
                    
                </div>
                <div class="col-md-3">
                    <a href="{{ path('app_equipe_index') }}" class="btn small club-top-btn">retour</a>
                </div>
            </div>
        </div>
        
<div class="championship-header-wrapper">
    <div class="container">
        <div class="row">
           
            <div class="col-md-3">
                <div class="club-info">
                    <div class="item"><span>Nom de l'equipe: </span>{{ equipe.nomEquipe }}</div>
                    <div class="item"><span>Nombre de joueurs: </span>{{ equipe.nbJoueurs }}</div>
                    <div class="item"><span>Site web: </span><a href="{{ equipe.siteWeb }}">{{ equipe.siteWeb }}</a></div>
                    <div class="item"><span>Date de creation: </span>{{ equipe.dateCreation|date("m/d/y") }}</div>
                     <a href="{{ path('app_equipe_like', { 'id': equipe.id }) }}" method="post" >
                            <i class="fa fa-regular fa-thumbs-up" style="font-size: 2em;"></i> 
                            </a> {{ numberLikes }}
                            

                            <a href="{{ path('app_equipe_dislike', { 'id': equipe.id }) }}" method="post">
                            <i class="fa fa-regular fa-thumbs-down" style="font-size: 2em;"></i> 
                            </a>{{ numberDislikes }}
                </div>
            </div>
            <div class="col-md-4">
                <div class="club-info">
                    <div class="item">Description de l'equipe: </div>
                    <p>{{ equipe.descriptionEquipe }}</p>
                </div>	
            </div>
        </div>	
    </div>	
</div>
    </section>

  

   

   
{% endblock %}