src/Entity/Sponsor.php
<?php

namespace App\Entity;

use App\Repository\SponsorRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\NotBlank;
#[ORM\Entity(repositoryClass: SponsorRepository::class)]
#[UniqueEntity(fields: ['nom_sponsor'], message: 'nom d equipe déja utilisé')]
class Sponsor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"veuillez choisir un nom de sponsor")]
    private ?string $nom_sponsor = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"veuillez choisir une description du sponsor")]
    private ?string $description_sponsor = null;

    #[ORM\Column(length: 255)]
     
    private ?string $logo_sponsor = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"veuillez choisir un site web")]
    private ?string $site_webs = null;

    #[ORM\ManyToOne(inversedBy: 'sponsors')]
    #[Assert\NotBlank(message:"veuillez choisir une equipe à sponsoriser")]
    private ?Equipe $id_equipe = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
     /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $date_creationn = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSponsor(): ?string
    {
        return $this->nom_sponsor;
    }

    public function setNomSponsor(string $nom_sponsor): self
    {
        $this->nom_sponsor = $nom_sponsor;

        return $this;
    }

    public function getDescriptionSponsor(): ?string
    {
        return $this->description_sponsor;
    }

    public function setDescriptionSponsor(string $description_sponsor): self
    {
        $this->description_sponsor = $description_sponsor;

        return $this;
    }

    public function getLogoSponsor(): ?string
    {
        return $this->logo_sponsor;
    }

    public function setLogoSponsor(string $logo_sponsor): self
    {
        $this->logo_sponsor = $logo_sponsor;

        return $this;
    }

    public function getSiteWebs(): ?string
    {
        return $this->site_webs;
    }

    public function setSiteWebs(string $site_webs): self
    {
        $this->site_webs = $site_webs;

        return $this;
    }

    public function getIdEquipe(): ?Equipe
    {
        return $this->id_equipe;
    }

    public function setIdEquipe(?Equipe $id_equipe): self
    {
        $this->id_equipe = $id_equipe;

        return $this;
    }

    public function getDateCreationn(): ?\DateTimeInterface
    {
        return $this->date_creationn;
    }
/**
     * @ORM\PrePersist()
     */
    public function setDateCreationn(\DateTimeInterface $date_creationn): self
    {
        $this->date_creationn = $date_creationn;

        return $this;
    }
}

src/Controller/SponsorbackController.php
<?php

namespace App\Controller;

use App\Entity\Sponsor;
use App\Form\Sponsor1Type;
use App\Form\SearchSponsorType;
use App\Repository\SponsorRepository;
use Doctrine\ORM\EntityManagerInterface;  
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/sponsorback')]
class SponsorbackController extends AbstractController
{
    #[Route('/allsponsors', name: 'json_allsponsors')]
    public function getSponsors(NormalizerInterface $normalizer, SponsorRepository $sponsorRepository): Response
    {
        $sponsor=$sponsorRepository->findAll();
        $sponsorNormalizer=$normalizer->normalize($sponsor,'json',['groups'=>"sponsors"]);
        $json=json_encode($sponsorNormalizer);
        return new Response($json);
    }

 #[Route('/addsponsor', name: 'json_addsponsor')]
    public function addSponsor(NormalizerInterface $normalizer, Request $req): Response
    {
        $em=$this->getDoctrine()->getManager();
        $sponsor=new Sponsor();

        $sponsor->setNomSponsor($req->get('nom_sponsor'));        
        $sponsor->setDescriptionSponsor($req->get('description_sponsor'));
        
        $sponsor->setLogoSponsor($req->get('logo_sponsor'));
        //$sponsor->setSiteWeb($req->get('site_webs'));
       // $sponsor->setIdEquipe($req->get('id_equipe'));
     
        $sponsor->setDateCreationn($req->get('date_creationn'));
        


        $em->persist($sponsor);
        $em->flush();
        $sponsorNormalizer=$normalizer->normalize($sponsor,'json',['groups'=>"sponsor"]);
        $json=json_encode($sponsorNormalizer);
        return new Response($json);
    }    

    #[Route('/modsponsor/{id}', name: 'json_modsponsor')]
    public function modifysponsor(NormalizerInterface $normalizer,$id, Request $req): Response
    {
        $em=$this->getDoctrine()->getManager();
        $sponsor=$em->getRepository(Sponsor::class)->find($id);
     
        $sponsor->setNomSponsor($req->get('nom_sponsor'));        
        $sponsor->setDescriptionSponsor($req->get('description_sponsor'));
       
        $sponsor->setLogoSponsor($req->get('logo_sponsor'));
        $sponsor->setSiteWeb($req->get('site_webs'));
       // $sponsor->setIdEquipe($req->get('id_equipe'));
     
        $sponsor->setDateCreationn($req->get('date_creationn'));
        
        $em->flush();
        $sponsorNormalizer=$normalizer->normalize($sponsor,'json',['groups'=>"sponsor"]);
        $json=json_encode($sponsorNormalizer);
        return new Response("Modification avec success".$json);
    }    

    #[Route('/delsponsor/{id}', name: 'json_delsponsor')]
    public function delsponsor(NormalizerInterface $normalizer, Request $req, $id): Response
    {
        $em=$this->getDoctrine()->getManager();
        $sponsor=$em->getRepository(Sponsor::class)->find($id);
        $em->remove($sponsor);
        $em->flush();
        $sponsorNormalizer=$normalizer->normalize($sponsor,'json',['groups'=>"sponsor"]);
        $json=json_encode($sponsorNormalizer);
        return new Response("Suppression avec success".$json);
    }


//////////////////////////////////////////////////////////////////////
#[Route('/', name: 'app_sponsorback_index', methods: ['GET', 'POST'])]
public function index(
    SponsorRepository $sponsorRepository,
    PaginatorInterface $paginator,
    Request $request,
    EntityManagerInterface $em
): Response
{
    $form = $this->createForm(SearchSponsorType::class);
    $form->handleRequest($request);

    $sortOrder = $request->query->get('sort_order', 'asc');
    $sortBy = $request->query->get('sort_by', 'nom_sponsor');

    // Create the query builder and add the orderBy clause
    $queryBuilder = $em->getRepository(Sponsor::class)->createQueryBuilder('s');
    $queryBuilder->orderBy("s.$sortBy", $sortOrder);
    $data = $sponsorRepository->findAll();
    $sponsors = $paginator->paginate (

      $queryBuilder,
      $request->query->getInt('page',1),
      2

    );
    if($form->isSubmitted() && $form->isValid()){
        $data = $form->getData();
        $query = $em->getRepository(Sponsor::class)
            ->createQueryBuilder('s')
            ->where('s.nom_sponsor LIKE :query')
            ->setParameter('query', "%{$data['query']}%")
            ->getQuery();

        $sponsors= $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            2
        );
        return $this->render('sponsorback/index.html.twig', [
            'form' => $form->createView(),
            'sponsors' => $sponsors,
            'sort_order' => $sortOrder,
        'sort_by' => $sortBy,   
        ]);
    }

    return $this->render('sponsorback/index.html.twig', [
        'form' => $form->createView(),
        'sponsors' => $sponsors,
        'sort_order' => $sortOrder,
        'sort_by' => $sortBy,
    ]);
    }

   
    #[Route('/new', name: 'app_sponsorback_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SponsorRepository $sponsorRepository): Response
    {
        $sponsor = new Sponsor();
        $form = $this->createForm(Sponsor1Type::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $file */
            $file = $form->get('logo_sponsor')->getData();

            // If a file was uploaded
            if ($file) {
                $filename = uniqid() . '.' . $file->guessExtension();

                // Move the file to the directory where brochures are stored
                $file->move(
                    'sponsorImages',
                    $filename
                );

                // Update the 'image' property to store the image file name
                // instead of its contents
                $sponsor->setLogoSponsor($filename);
            }
            $sponsor->setDateCreationn(new \DateTime());
            $sponsorRepository->save($sponsor, true);
            $session = $this->get('session');
             $session->getFlashBag()->clear();
             $this->addFlash('success','Ajout effectué');
            return $this->redirectToRoute('app_sponsorback_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('sponsorback/new.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form,
        ]);
    }
    #[Route('/{id}', name: 'app_sponsorback_show', methods: ['GET'])]
    public function show(Sponsor $sponsor): Response
    {
        return $this->render('sponsorback/show.html.twig', [
            'sponsor' => $sponsor,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_sponsorback_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Sponsor $sponsor, SponsorRepository $sponsorRepository): Response
    {
        $image=$sponsor->getLogoSponsor();
        $form = $this->createForm(Sponsor1Type::class, $sponsor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             /** @var UploadedFile $file */
             $file = $form->get('logo_sponsor')->getData();

             // If a file was uploaded
             if ($file) {
                 $filename = uniqid() . '.' . $file->guessExtension();
                 $file->move(
                     'sponsorImages',
                     $filename
                 );
                 $sponsor->setLogoSponsor($filename);
             }else{
               $sponsor->setLogoSponsor($image);
           }
             
            $sponsorRepository->save($sponsor, true);
            $session = $this->get('session');
            $session->getFlashBag()->clear();
            $this->addFlash('update','Modification effectué');  
            return $this->redirectToRoute('app_sponsorback_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sponsorback/edit.html.twig', [
            'sponsor' => $sponsor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_sponsorback_delete', methods: ['POST'])]
    public function delete(Request $request, Sponsor $sponsor, SponsorRepository $sponsorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sponsor->getId(), $request->request->get('_token'))) {
            $sponsorRepository->remove($sponsor, true);
            $session = $this->get('session');
            $session->getFlashBag()->clear();
            $this->addFlash('delete','Suppression effectué');
        }

        return $this->redirectToRoute('app_sponsorback_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/sponsorback/_delete_form.html.twig
<form method="post" action="{{ path('app_sponsorback_delete', {'id': sponsor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sponsor.id) }}">
    <button class="badge badge-danger" class="btn"></button>
</form>

templates/sponsorback/_form.html.twig
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
        <h4 class="card-title"></h4>
        <p class="card-description"> <br></p>
{{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
  <h1>Sponsor</h1>

<div class="form-group">
        <div class="form-group">
        {{ form_label(form.nom_sponsor,"Nom du sponsor") }}
        {{ form_widget(form.nom_sponsor,{'attr': {'class': 'form-control'}})}}
        {{ form_errors(form.nom_sponsor) }}
        </div>
 
 <div class="form-group">
        <div class="form-group">
        {{ form_label(form.description_sponsor,"description du sponsor") }}
        {{ form_widget(form.description_sponsor,{'attr': {'class': 'form-control'}})}}
        {{ form_errors(form.description_sponsor) }}
        </div>

        <div class="form-group">
        <div class="form-group">
        {{ form_label(form.logo_sponsor,"logo sponsor") }}
        {{ form_widget(form.logo_sponsor,{'attr': {'class': 'form-control'}})}}
        {{ form_errors(form.logo_sponsor) }}
        </div>

        <div class="form-group">
        <div class="form-group">
        {{ form_label(form.site_webs,"SITE WEB") }}
        {{ form_widget(form.site_webs,{'attr': {'class': 'form-control'}})}}
        {{ form_errors(form.site_webs) }}
        </div>

        <div class="form-group">
        <div class="form-group">
        {{ form_label(form.id_equipe,"Nom équipe sponsorisée") }}
        {{ form_widget(form.id_equipe,{'attr': {'class': 'form-control'}})}}
        {{ form_errors(form.id_equipe) }}
        </div>

   <button class="btn btn-primary mr-2">{{ button_label|default('Enregistrer') }}</button>
        <a class="btn btn-primary mr-2" href="{{ path('app_sponsorback_index') }}">Retour à la liste</a>
{{ form_end(form) }}

  </div>
    </div>
</div>

templates/sponsorback/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Edit Sponsor{% endblock %}

{% block body %}
    <h1>Edit Sponsor</h1>

    {{ include('sponsorback/_form.html.twig', {'button_label': 'modifier'}) }}

   

   
{% endblock %}

templates/sponsorback/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Table de sponsors{% endblock %}

{% block body %}
<div class="main-panel">
    {% if app.flashes('success') is not empty %}
    <div class="alert alert-success notification" role="alert">
       <center>sponsor ajouté avec succès</center>
         
        <script>
            setTimeout(function() {
                document.querySelector('.alert').style.display = 'none';
            }, 3000);
        </script>
    </div>
{% endif %}
{% if app.flashes('update') is not empty %}
    <div class="alert alert-success notification" role="alert">
       <center>sponsor modifié avec succès</center>
         
        <script>
            setTimeout(function() {
                document.querySelector('.alert').style.display = 'none';
            }, 3000);
        </script>
    </div>
{% endif %}
 {% if app.flashes('delete') is not empty %}
    <div class="alert alert-success notification" role="alert">
       <center>sponsor supprimé avec succès</center>
         
        <script>
            setTimeout(function() {
                document.querySelector('.alert').style.display = 'none';
            }, 3000);
        </script>
    </div>
{% endif %}
   <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"> Sponsors </h3>
               <th><a href="{{ path('app_sponsorback_index', {'sort_by': 'nom_sponsor', 'sort_order': sort_order == 'asc' ? 'desc' : 'asc' }) }}" class="btn btn-primary" >trier par nom</a></th>
               <th><a href="{{ path('app_sponsorback_index', {'sort_by': 'date_creationn', 'sort_order': sort_order == 'asc' ? 'desc' : 'asc' }) }}" class="btn btn-primary" >trier par date</a></th>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#"></a></li>
                </ol>
              </nav>
            </div>
             {{form_start(form)}}
                    {{form_widget(form.query)}}
                    
                    <button class="btn btn-primary"  type="submit" >chercher</button>
                {{form_end(form)}}
                <div><p> </p> </div>
              <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Table des sponsors</h4>
                    <div class="d-flex justify-content-end mt-3 mb-3">
                        <a href="{{ path('app_sponsorback_new') }}" class="btn btn-success">Ajout</a>
                        </div>
                    <div class="table-responsive">
                      <table class="table table-striped">
                        <thead>
            <tr>
               
                <th>Logo du sponsor</th>
                <th>Nom du sponsor</th>               
                <th>Site web</th>
                <th>Nom équipe sponsoriseé</th>
                <th>Date de creation</th> 
                <th>actions</th>
                <th>Détails</th>
            </tr>
        </thead>
        <tbody>
        {% for sponsor in sponsors %}
            <tr>
                
                <td><a  class="custom-logo-link"><img src="{{asset('sponsorImages/'~sponsor.logoSponsor)}}" alt="logo" class="custom-logo"></a></td>
                <td>{{ sponsor.nomSponsor }}</td>          
                <td>{{ sponsor.siteWebs }}</td>
                <td>{{ sponsor.IdEquipe }}</td>
                <td>{{sponsor.dateCreationn ? sponsor.dateCreationn|date('Y-m-d ') }}</td>
                <td>
                  <a class="btn btn-primary" href="{{ path('app_sponsorback_edit', {'id': sponsor.id}) }}"><i class="mdi mdi-pencil"></i></a>
                     <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ loop.index }}">
                <i class="mdi mdi-delete"></i>
            </button>
<!-- Delete Modal -->
<div class="modal fade" id="deleteModal{{ loop.index }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirmation du supprission</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                Êtes-vous sûr de vouloir supprimer cet élément?
            </div>

            <div class="modal-footer">
                <form method="post" action="{{ path('app_sponsorback_delete', {'id': sponsor.id}) }}">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sponsor.id) }}">
                    <button type="submit" class="btn btn-danger">oui</button>
                </form>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
            </div>

        </div>
    </div>
</div>
                </td>
                <td>
                  <a class="btn btn-primary" href="{{ path('app_sponsorback_show', {'id': sponsor.id}) }}"><i class="mdi mdi-view-headline"></i></a>
                  </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun enregistrement trouvé</td>
            </tr>
    
        </tbody>
        {% endfor %}
    </table>
        
                     </div>
                  </div>
                </div>
                     
              </div>
        <div class="moved">
 {% do sponsors.setPageRange(2) %}
 {{knp_pagination_render(sponsors , 'sponsorback/pagination.html.twig')}}
 </div>
        </div>
            </div>
        </div>
             
                </div>
                     
              </div>
            </div>
        </div>
        </div>
        <script src="{{asset('assets/vendors/js/vendor.bundle.base.js')}}"> </script>
	<!-- endinject -->
	<!-- Plugin js for this page -->
	<!-- End plugin js for this page -->
	<!-- inject:js --><script src="{{asset('js/off-canvas.js')}}"> </script>
	<script src="{{asset('js/hoverable-collapse.js')}}"></script>
<script src="{{asset('js/misc.js')}}"></script>
	<script src="{{asset('js/settings.js')}}"></script>
	<script src="{{asset('js/todolist.js')}}"></script>
    <script src="{{asset('assets/vendorsassets/js/vendor.bundle.base.js')}}"></script>
			<!-- endinject -->
			<!-- Plugin js for this page -->
			<script src="{{asset('assets/vendors/chart.js/Chart.min.js')}}"></script>
			<script src="{{asset('assets/vendors/progressbar.js/progressbar.min.js')}}"></script>
			<script src="{{asset('assets/vendors/jvectormap/jquery-jvectormap.min.js')}}"></script>
			<script src="{{asset('assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
			<script src="{{asset('assets/vendors/owl-carousel-2/owl.carousel.min.js')}}"></script>
			<!-- End plugin js for this page -->
			<!-- inject:js -->
			<script src="{{asset('assets/js/off-canvas.js')}}"></script>
			<script src="{{asset('assets/js/hoverable-collapse.js')}}"></script>
			<script src="{{asset('assets/js/misc.js')}}"></script>
			<script src="{{asset('assets/js/settings.js')}}"></script>
			<script src="{{asset('assets/js/todolist.js')}}"></script>
			<!-- endinject -->
			<!-- Custom js for this page -->
			<script src="{{asset('assets/js/dashboard.js')}}"></script>
{% endblock %}

templates/sponsorback/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}New Sponsor{% endblock %}

{% block body %}
    {{ form_start(form) }}

    {{ include('sponsorback/_form.html.twig') }}

    
    {{form_end(form)}}
{% endblock %}

templates/sponsorback/pagination.html.twig
{% if pageCount > 1 %}
    <nav>
        {% set classAlign = (align is not defined) ? '' : align=='center' ? ' justify-content-center' : (align=='right' ? ' justify-content-end' : '') %}
        {% set classSize = (size is not defined) ? '' : size=='large' ? ' pagination-lg' : (size=='small' ? ' pagination-sm' : '') %}
        <ul class="pagination{{ classAlign }}{{ classSize }}">

            {% if previous is defined %}
                <li class="page-item">
                    <a class="page-link" rel="prev" href="{{ path(route, query|merge({(pageParameterName): previous})) }}">&laquo;&nbsp;{{ 'précédent'|trans({}, 'KnpPaginatorBundle') }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;&nbsp;{{ 'précédent'|trans({}, 'KnpPaginatorBundle') }}</span>
                </li>
            {% endif %}

            {% if startPage > 1 %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 1})) }}">1</a>
                </li>
                {% if startPage == 3 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 2})) }}">2</a>
                    </li>
                {% elseif startPage != 2 %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% endif %}
            {% endif %}

            {% for page in pagesInRange %}
                {% if page != current %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <span class="page-link">{{ page }}</span>
                    </li>
                {% endif %}

            {% endfor %}

            {% if pageCount > endPage %}
                {% if pageCount > (endPage + 1) %}
                    {% if pageCount > (endPage + 2) %}
                        <li class="page-item disabled">
                            <span class="page-link">&hellip;</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): (pageCount - 1)})) }}">{{ pageCount -1 }}</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): pageCount})) }}">{{ pageCount }}</a>
                </li>
            {% endif %}

            {% if next is defined %}
                <li class="page-item">
                    <a class="page-link" rel="next" href="{{ path(route, query|merge({(pageParameterName): next})) }}">{{ 'suivant'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</a>
                </li>
            {% else %}
                <li  class="page-item disabled">
                    <span class="page-link">{{ 'suivant'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/sponsorback/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}Sponsor{% endblock %}

{% block body %}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
        <h4 class="card-title"></h4>
        <p class="card-description"> <br></p>

    <h1>Détails Sponsor</h1>
<div> <p> </p> </div>
    <div> <p> </p> </div>
    <table class="table">
        <tbody>
           
            <tr>
                <th>Logo_sponsor</th>
                <td><a  class="custom-logo-link"><img src="{{asset('sponsorImages/'~sponsor.logoSponsor)}}" alt="logo" class="custom-logo"></a></td>
            </tr>
            <tr>
                <th>Nom_sponsor</th>
                <td>{{ sponsor.nomSponsor }}</td>
            </tr>
            <tr>
                <th>Description_sponsor</th>
                <td>{{ sponsor.descriptionSponsor }}</td>
            </tr>
            <tr>
                <th>Site_web</th>
                   <td><a href="{{ sponsor.siteWebs }}">{{ sponsor.siteWebs }}</a></td>
            </tr>
<tr>
                <th>Nom équipe sponsoriseé</th>
                <td>{{ sponsor.IdEquipe }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ sponsor.dateCreationn|date('Y-m-d ') }}</td>
            </tr>
        </tbody>
    </table>
<div> <p> </p> </div>
    <div> <p> </p> </div>
    <a class="btn btn-primary mr-2" href="{{ path('app_sponsorback_index') }}">Retour à la liste</a>

    

    
{% endblock %}